#!/usr/bin/env node
// horde skill — node.mjs
//
// The only tool that knows which graph mode a horde runs in. With Yggdrasil, node ids, boundaries
// and descriptions are read from .yggdrasil/model/**/yg-node.yaml (never written by this tool —
// the architect files graph changes through `yg`, with the user's confirmation where the repo's
// own rules require it); charter.md and contracts.md live beside the yaml, committed. Without it
// (config.nodeSource = "manual"), this tool is the sole writer of the whole committed node map
// under <graphDir>/nodes/<node>/. Either way, graph *proposals* and contract negotiations are
// operational state — uncommitted, per horde, in hordes/<horde>/graph.json — until an approval
// turns one into a committed charter/contracts.md write (manual) or a `yg` filing the architect
// runs by hand (Yggdrasil).

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { execFileSync } from 'node:child_process';
import {
  repoRoot, hordePath, readJSON, writeJSON, readText, writeText, appendText, readConfig, nowIso,
  fail, parseArgs, asArray, emit, isMain, resolveHorde, renderTemplate,
} from './_lib.mjs';
import { trace as traceRoster } from './roster.mjs';

const USAGE = `usage: node.mjs <command> [options]

commands:
  bind [--horde h]
      verifies the graph is readable; lists every node id.
  map [--horde h]
      this mission's nodes (named by an owner in the roster or by a ticket) with owner, stamp,
      open contract proposals.
  show <node> [--horde h]
      boundary, charter, contracts, last log entries, stamp.
  charter edit <node> [--horde h]
      writes charter.md from stdin; seeds it from the template first when the node has none yet
      and stdin is empty.
  log <node> "<reason>" [--run] [--horde h]
      manual mode: appends to the node's log.md. Yggdrasil mode: prints the "yg log add --reason"
      command; runs it too when --run is given.
  stamp <node> <sha> [--horde h]
      manual mode: records verifiedAt on the node. Yggdrasil mode: the graph computes its own
      verification status — this prints how to refresh it instead of writing anything.
  contract propose <a> <b> --as <path> "<text>" [--horde h]
  contract approve <id> ["why"] --by <name> [--horde h]
  contract veto <id> "why" --by <name> [--horde h]
  contracts [--pending] [--node n] [--horde h]
  propose <kind> "<text>" --by <owner> [--node n] [--boundary <glob>[,glob…]] [--horde h]
      kinds: new-node, move-boundary, rename, rule. move-boundary requires --node and --boundary
      so apply can carry it out later, not just record that it happened.
  proposals [--open] [--horde h]
  approve <id> ["why"] --by <name> [--horde h]
  veto <id> "why" --by <name> [--horde h]
  new <node> --boundary <glob>[,glob…] [--depends a,b] [--horde h]
      manual mode only: creates the node's committed files. Yggdrasil mode prints the yg-side
      steps instead (they need the user's confirmation).
  boundary set <node> --boundary <glob>[,glob…] [--horde h]
  boundary add <node> --boundary <glob>[,glob…] [--horde h]
      manual mode: rewrites (set) or extends (add) node.json's boundary, logs the change.
      Yggdrasil mode prints the yg-side steps instead.
  apply <proposal-id> [--horde h]
      manual mode only: closes an approved graph-change proposal. Yggdrasil mode prints the
      filing steps instead.

options: --json  --help`;

// ---- mode ----------------------------------------------------------------

function mode(cfg) {
  return cfg && cfg.nodeSource === 'yggdrasil' ? 'yggdrasil' : 'manual';
}

function graphDir(cfg) {
  return (cfg && cfg.graphDir) || 'architecture/';
}

function manualNodeDir(root, cfg, node) {
  return join(root, graphDir(cfg).replace(/\/$/, ''), 'nodes', node);
}

function yggdrasilNodeDir(root, node) {
  return join(root, '.yggdrasil', 'model', node);
}

function nodeDir(root, cfg, node) {
  return mode(cfg) === 'yggdrasil' ? yggdrasilNodeDir(root, node) : manualNodeDir(root, cfg, node);
}

// ---- manual mode: node.json -----------------------------------------------

function manualNodeJsonPath(root, cfg, node) {
  return join(manualNodeDir(root, cfg, node), 'node.json');
}

function readManualNode(root, cfg, node) {
  return readJSON(manualNodeJsonPath(root, cfg, node), null);
}

// ---- yggdrasil mode: a minimal, targeted yg-node.yaml reader --------------
//
// Not a general YAML parser — this repository's yg-node.yaml files are generated by `yg` in a
// narrow, predictable shape (scalar fields, `mapping:`/`aspects:` as flat dash-lists, `relations:`
// as a dash-list of {type, target} pairs), and node.mjs only ever reads this file, never writes
// it. A parser that tried to be a general YAML implementation would be both larger and no more
// correct for the one shape it actually has to handle.
function parseYgNodeYaml(text) {
  const lines = text.split('\n');
  const result = { name: null, type: null, description: null, mapping: [], relations: [] };
  let section = null;
  let pendingRelation = null;
  const flushRelation = () => {
    if (pendingRelation && (pendingRelation.target || pendingRelation.type)) result.relations.push(pendingRelation);
    pendingRelation = null;
  };
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '');
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const topMatch = /^([A-Za-z_-]+):\s*(.*)$/.exec(line);
    if (topMatch && !line.startsWith(' ')) {
      flushRelation();
      const [, key, rest] = topMatch;
      if (key === 'name') result.name = unquote(rest.trim());
      else if (key === 'type') result.type = unquote(rest.trim());
      else if (key === 'description') result.description = unquote(rest.trim());
      section = ['mapping', 'aspects', 'relations'].includes(key) ? key : null;
      continue;
    }
    if (section === 'mapping') {
      const m = /^\s*-\s*(.+)$/.exec(line);
      if (m) result.mapping.push(unquote(m[1].trim()));
      continue;
    }
    if (section === 'relations') {
      const dash = /^\s*-\s*(.+)$/.exec(line);
      const kv = /^\s+([A-Za-z_-]+):\s*(.*)$/.exec(line);
      if (dash) {
        flushRelation();
        pendingRelation = {};
        const inline = /^([A-Za-z_-]+):\s*(.*)$/.exec(dash[1]);
        if (inline) pendingRelation[inline[1]] = unquote(inline[2].trim());
      } else if (kv && pendingRelation) {
        pendingRelation[kv[1]] = unquote(kv[2].trim());
      }
      continue;
    }
  }
  flushRelation();
  return result;
}

function unquote(s) {
  if (s.length >= 2 && s.startsWith('"') && s.endsWith('"')) return s.slice(1, -1);
  return s;
}

function readYggdrasilNode(root, node) {
  const file = join(yggdrasilNodeDir(root, node), 'yg-node.yaml');
  const text = readText(file);
  if (!text) return null;
  return parseYgNodeYaml(text);
}

// ---- shared node reads (exported for brief.mjs / premerge.mjs) ------------

export function nodeExists(root, cfg, node) {
  if (mode(cfg) === 'yggdrasil') return existsSync(join(yggdrasilNodeDir(root, node), 'yg-node.yaml'));
  return existsSync(manualNodeJsonPath(root, cfg, node));
}

export function listAllNodes(root, cfg) {
  if (mode(cfg) === 'yggdrasil') {
    const base = join(root, '.yggdrasil', 'model');
    const found = [];
    const walk = (dir) => {
      if (!existsSync(dir)) return;
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, e.name);
        if (e.isDirectory()) walk(full);
        else if (e.name === 'yg-node.yaml') found.push(relative(base, dir));
      }
    };
    walk(base);
    return found.sort();
  }
  const dir = join(root, graphDir(cfg).replace(/\/$/, ''), 'nodes');
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort();
}

// boundary — array of path globs the node covers.
export function nodeBoundary(root, cfg, node) {
  if (mode(cfg) === 'yggdrasil') {
    const y = readYggdrasilNode(root, node);
    return y ? y.mapping : [];
  }
  const n = readManualNode(root, cfg, node);
  return n && Array.isArray(n.boundary) ? n.boundary : [];
}

// The repo-root-relative directory a node's own graph files live in (yg-node.yaml, charter.md,
// contracts.md, log.md in Yggdrasil mode; node.json and the same three .md files in manual mode),
// trailing slash included — the prefix premerge.mjs's scope check treats as inside a ticket's
// node, alongside its code boundary. Nothing else under .yggdrasil/ (yg-architecture.yaml,
// aspects, locks, config) is a node's own files, so this names only that one directory, never
// the graph root.
export function nodeGraphPathPrefix(root, cfg, node) {
  return `${relative(root, nodeDir(root, cfg, node))}/`;
}

export function nodeCharterPath(root, cfg, node) {
  return join(nodeDir(root, cfg, node), 'charter.md');
}

export function nodeContractsPath(root, cfg, node) {
  return join(nodeDir(root, cfg, node), 'contracts.md');
}

export function readNodeCharterText(root, cfg, node) {
  return readText(nodeCharterPath(root, cfg, node));
}

export function readNodeContractsText(root, cfg, node) {
  return readText(nodeContractsPath(root, cfg, node));
}

// ---- operational graph.json: proposals + contracts + stamps ---------------

function graphJsonPath(horde) {
  return hordePath(horde, 'graph.json');
}

function loadGraph(horde) {
  const doc = readJSON(graphJsonPath(horde), null);
  return {
    proposals: doc && Array.isArray(doc.proposals) ? doc.proposals : [],
    contracts: doc && Array.isArray(doc.contracts) ? doc.contracts : [],
    stamps: doc && doc.stamps && typeof doc.stamps === 'object' ? doc.stamps : {},
  };
}

function saveGraph(horde, graph) {
  writeJSON(graphJsonPath(horde), graph);
}

function nextId(items) {
  let max = 0;
  for (const it of items) { const n = Number(it.id); if (Number.isFinite(n)) max = Math.max(max, n); }
  return String(max + 1);
}

// ---- contracts.md rendering (per node, from graph.json — the source of truth) --

function renderContractsTable(node, contracts) {
  const rows = contracts.filter((c) => c.a === node || c.b === node);
  const lines = [
    `# Contracts · ${node}`, '',
    '| id | with | promise | expressed as | status |', '|---|---|---|---|---|',
  ];
  if (rows.length === 0) lines.push('| | | | | |');
  for (const c of rows) {
    const other = c.a === node ? c.b : c.a;
    lines.push(`| ${c.id} | ${other} | ${c.text} | ${c.as} | ${c.status} |`);
  }
  return lines.join('\n') + '\n';
}

function writeContractsMd(root, cfg, horde, node, contracts) {
  if (!nodeExists(root, cfg, node)) return; // nothing to write beside yet
  writeText(nodeContractsPath(root, cfg, node), renderContractsTable(node, contracts));
}

// ---- commands ---------------------------------------------------------------

function cmdBind(root, cfg, flags) {
  const nodes = listAllNodes(root, cfg);
  emit({ mode: mode(cfg), nodes }, flags, () => `graph readable (${mode(cfg)}) — ${nodes.length} node(s): ${nodes.join(', ') || '(none)'}`);
}

// Nodes "this mission touches": named by an owner in the roster, or by a ticket anywhere under
// teams/**/issues/*/issue.md (walked recursively for sub-teams).
function missionNodes(horde, root, cfg) {
  const nodes = new Set();
  const roster = readJSON(hordePath(horde, 'roster.json'), { entries: [] });
  for (const e of asArray(roster.entries)) {
    if (e.role === 'owner' && e.node) nodes.add(e.node);
  }
  const teamsRoot = hordePath(horde, 'teams');
  const walk = (teamDir) => {
    const issuesDir = join(teamDir, 'issues');
    if (existsSync(issuesDir)) {
      for (const d of readdirSync(issuesDir, { withFileTypes: true })) {
        if (!d.isDirectory()) continue;
        const text = readText(join(issuesDir, d.name, 'issue.md'));
        for (const n of ticketNodes(text)) nodes.add(n);
      }
    }
    const subTeamsDir = join(teamDir, 'teams');
    if (existsSync(subTeamsDir)) {
      for (const d of readdirSync(subTeamsDir, { withFileTypes: true })) {
        if (d.isDirectory()) walk(join(subTeamsDir, d.name));
      }
    }
  };
  if (existsSync(teamsRoot)) {
    for (const d of readdirSync(teamsRoot, { withFileTypes: true })) {
      if (d.isDirectory()) walk(join(teamsRoot, d.name));
    }
  }
  return [...nodes].sort();
}

// The **Node:** field of a rendered ticket.md — one node, or several comma-separated for a
// contract ticket (`tk.mjs new` accepts a repeatable --node; nothing in the shared templates
// fixes a multi-node separator, so this reads the plain, unambiguous one: comma-separated).
export function ticketNodes(issueText) {
  if (!issueText) return [];
  const m = /\*\*Node:\*\*\s*([^·\n]+)·/.exec(issueText) || /\*\*Node:\*\*\s*([^\n]+)/.exec(issueText);
  if (!m) return [];
  return m[1].split(',').map((s) => s.trim()).filter(Boolean);
}

function ownerOf(horde, node) {
  const roster = readJSON(hordePath(horde, 'roster.json'), { entries: [] });
  const owners = asArray(roster.entries).filter((e) => e.role === 'owner' && e.node === node && e.state !== 'dead' && e.state !== 'retired');
  return owners.length ? owners[owners.length - 1].name : '-';
}

function stampOf(root, cfg, horde, node) {
  if (mode(cfg) === 'yggdrasil') {
    const graph = loadGraph(horde);
    return graph.stamps[node] ? `${graph.stamps[node].sha} (horde-recorded — see yg check for the graph's own status)` : 'graph-managed — see yg check';
  }
  const n = readManualNode(root, cfg, node);
  return n && n.verifiedAt ? `${n.verifiedAt.sha} @ ${n.verifiedAt.at}` : 'unverified';
}

function cmdMap(horde, root, cfg, flags) {
  const nodes = missionNodes(horde, root, cfg);
  const graph = loadGraph(horde);
  const rows = nodes.map((node) => ({
    node,
    owner: ownerOf(horde, node),
    stamp: stampOf(root, cfg, horde, node),
    openProposals: graph.contracts.filter((c) => (c.a === node || c.b === node) && c.status === 'proposed').length,
  }));
  emit(rows, flags, () => {
    if (rows.length === 0) return '(no nodes touched yet)';
    return rows.map((r) => `${r.node}  owner=${r.owner}  stamp=${r.stamp}  open-proposals=${r.openProposals}`).join('\n');
  });
}

function cmdShow(horde, root, cfg, positional, flags) {
  const node = positional[0];
  if (!node) fail('show requires <node>');
  if (!nodeExists(root, cfg, node)) fail(`no such node: ${node}`);
  const boundary = nodeBoundary(root, cfg, node);
  const charter = readNodeCharterText(root, cfg, node) || '(no charter yet)';
  const contracts = readNodeContractsText(root, cfg, node) || renderContractsTable(node, loadGraph(horde).contracts);
  let log = '(no log yet)';
  if (mode(cfg) === 'yggdrasil') {
    try {
      log = execFileSync('yg', ['log', 'read', '--node', node], { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim() || log;
    } catch { /* yg not on PATH or no entries yet — keep the placeholder */ }
  } else {
    const text = readText(join(manualNodeDir(root, cfg, node), 'log.md'));
    if (text) log = text.trim();
  }
  const stamp = stampOf(root, cfg, horde, node);
  const result = { node, boundary, charter, contracts, log, stamp };
  emit(result, flags, () => [
    `# ${node}`, '',
    `**Boundary:** ${boundary.join(', ') || '(none)'}`,
    `**Stamp:** ${stamp}`, '',
    '## Charter', charter, '',
    '## Contracts', contracts, '',
    '## Log', log,
  ].join('\n'));
}

function readStdin() {
  try {
    return readFileSync(0, 'utf8');
  } catch {
    return '';
  }
}

function cmdCharterEdit(horde, root, cfg, positional, flags) {
  const node = positional[0];
  if (!node) fail('charter edit requires <node>');
  const stdin = readStdin();
  const exists = nodeExists(root, cfg, node);
  let content = stdin;
  if (!content.trim()) {
    if (exists) fail('charter edit requires content on stdin');
    content = renderTemplate('node-charter', {
      node, owner: '(unassigned)', class: '(unassigned)', lease: '(unassigned)',
    });
  }
  if (!exists) {
    if (mode(cfg) === 'manual') {
      writeJSON(manualNodeJsonPath(root, cfg, node), { id: node, boundary: [], dependsOn: [], verifiedAt: null });
      writeText(nodeContractsPath(root, cfg, node), renderContractsTable(node, loadGraph(horde).contracts));
      writeText(join(manualNodeDir(root, cfg, node), 'log.md'), `# Log · ${node}\n\n`);
    } else {
      fail(`no such node in the Yggdrasil graph: ${node} — a new node is filed with \`yg\` by the architect, not seeded here`);
    }
  }
  writeText(nodeCharterPath(root, cfg, node), content);
  emit({ node, bytes: content.length }, flags, () => `charter written: ${node} (${content.length} bytes)`);
}

function cmdLog(horde, root, cfg, positional, flags) {
  const [node, reason] = positional;
  if (!node || !reason) fail('log requires <node> "<reason>"');
  if (mode(cfg) === 'yggdrasil') {
    const cmd = `yg log add --node ${node} --reason "${reason.replace(/"/g, '\\"')}"`;
    if (flags.run) {
      try {
        execFileSync('yg', ['log', 'add', '--node', node, '--reason', reason], { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] });
      } catch (e) {
        fail(`yg log add failed: ${e.message}`);
      }
      emit({ node, reason, ran: true }, flags, () => `ran: ${cmd}`);
      return;
    }
    emit({ node, reason, command: cmd }, flags, () => cmd);
    return;
  }
  if (!nodeExists(root, cfg, node)) fail(`no such node: ${node}`);
  appendText(join(manualNodeDir(root, cfg, node), 'log.md'), `## [${nowIso()}]\n${reason}\n\n`);
  emit({ node, reason }, flags, () => `logged: ${node}`);
}

function cmdStamp(horde, root, cfg, positional, flags) {
  const [node, sha] = positional;
  if (!node || !sha) fail('stamp requires <node> <sha>');
  if (mode(cfg) === 'yggdrasil') {
    emit(
      { node, sha, written: false },
      flags,
      () => `Yggdrasil computes its own verification status for ${node} — this is not written here. `
        + `Run \`yg check --node ${node}\` (or \`yg aspect-test --node ${node}\`) to refresh it.`,
    );
    return;
  }
  if (!nodeExists(root, cfg, node)) fail(`no such node: ${node}`);
  const n = readManualNode(root, cfg, node);
  n.verifiedAt = { sha, at: nowIso() };
  writeJSON(manualNodeJsonPath(root, cfg, node), n);
  emit({ node, sha }, flags, () => `stamped: ${node} @ ${sha}`);
}

// ---- contracts --------------------------------------------------------------

function cmdContractPropose(horde, root, cfg, positional, flags) {
  const [a, b, text] = positional;
  if (!a || !b || !text) fail('contract propose requires <a> <b> "<text>"');
  if (!flags.as) fail('contract propose requires --as <test-or-scenario-path>');
  const graph = loadGraph(horde);
  const entry = {
    id: nextId(graph.contracts), a, b, as: flags.as, text, status: 'proposed', by: flags.by || null, at: nowIso(),
  };
  graph.contracts.push(entry);
  saveGraph(horde, graph);
  writeContractsMd(root, cfg, horde, a, graph.contracts);
  writeContractsMd(root, cfg, horde, b, graph.contracts);
  emit(entry, flags, () => `contract proposed: [${entry.id}] ${a} <-> ${b}`);
}

function cmdContractRule(horde, root, cfg, positional, flags, verdict) {
  const [id, why] = positional;
  if (!id) fail(`contract ${verdict === 'approved' ? 'approve' : 'veto'} requires <id>`);
  if (!flags.by) fail('--by is required');
  const graph = loadGraph(horde);
  const c = graph.contracts.find((x) => x.id === id);
  if (!c) fail(`no such contract: ${id}`);
  if (c.status !== 'proposed') fail(`contract ${id} is already ${c.status}`);
  c.status = verdict;
  c.ruling = why || null;
  c.rulingBy = flags.by;
  c.ruledAt = nowIso();
  saveGraph(horde, graph);
  writeContractsMd(root, cfg, horde, c.a, graph.contracts);
  writeContractsMd(root, cfg, horde, c.b, graph.contracts);
  traceRoster(horde, flags.by);
  emit(c, flags, () => `contract ${id} ${verdict}`);
}

function cmdContracts(horde, positional, flags) {
  const graph = loadGraph(horde);
  let rows = graph.contracts;
  if (flags.pending) rows = rows.filter((c) => c.status === 'proposed');
  if (flags.node) rows = rows.filter((c) => c.a === flags.node || c.b === flags.node);
  emit(rows, flags, () => {
    if (rows.length === 0) return '(none)';
    return rows.map((c) => `[${c.id}] ${c.a} <-> ${c.b}  ${c.status}  ${c.text}`).join('\n');
  });
}

// ---- graph-change proposals ---------------------------------------------------

const PROPOSAL_KINDS = ['new-node', 'move-boundary', 'rename', 'rule'];

function parseBoundaryList(v) {
  return String(v).split(',').map((s) => s.trim()).filter(Boolean);
}

function cmdPropose(horde, positional, flags) {
  const [kind, text] = positional;
  if (!kind || !text) fail(`propose requires <kind> "<text>" (kinds: ${PROPOSAL_KINDS.join(', ')})`);
  if (!PROPOSAL_KINDS.includes(kind)) fail(`unknown kind: ${kind} (kinds: ${PROPOSAL_KINDS.join(', ')})`);
  if (!flags.by) fail('propose requires --by <owner>');
  if (kind === 'move-boundary' && (!flags.node || !flags.boundary)) {
    fail('propose move-boundary requires --node <n> --boundary <glob>[,glob…], so apply can carry it out');
  }
  const graph = loadGraph(horde);
  const entry = {
    id: nextId(graph.proposals),
    kind,
    text,
    by: flags.by,
    status: 'open',
    at: nowIso(),
    node: flags.node || null,
    boundary: flags.boundary ? parseBoundaryList(flags.boundary) : null,
  };
  graph.proposals.push(entry);
  saveGraph(horde, graph);
  emit(entry, flags, () => `proposed: [${entry.id}] ${kind}`);
}

function cmdProposals(horde, flags) {
  const graph = loadGraph(horde);
  let rows = graph.proposals;
  if (flags.open) rows = rows.filter((p) => p.status === 'open');
  emit(rows, flags, () => {
    if (rows.length === 0) return '(none)';
    return rows.map((p) => `[${p.id}] ${p.kind}  ${p.status}  by ${p.by}  ${p.text}`).join('\n');
  });
}

function cmdProposalRule(horde, positional, flags, verdict) {
  const [id, why] = positional;
  if (!id) fail(`${verdict === 'approved' ? 'approve' : 'veto'} requires <id>`);
  if (!flags.by) fail('--by is required');
  const graph = loadGraph(horde);
  const p = graph.proposals.find((x) => x.id === id);
  if (!p) fail(`no such proposal: ${id}`);
  if (p.status !== 'open') fail(`proposal ${id} is already ${p.status}`);
  p.status = verdict;
  p.ruling = why || null;
  p.rulingBy = flags.by;
  p.ruledAt = nowIso();
  saveGraph(horde, graph);
  traceRoster(horde, flags.by);
  emit(p, flags, () => `proposal ${id} ${verdict}`);
}

// ---- manual-only new / apply (yggdrasil prints instead of acting) -----------

function cmdNew(horde, root, cfg, positional, flags) {
  const node = positional[0];
  if (!node) fail('new requires <node>');
  if (!flags.boundary) fail('new requires --boundary <glob>[,glob…]');
  const boundary = parseBoundaryList(flags.boundary);
  const dependsOn = flags.depends ? parseBoundaryList(flags.depends) : [];

  if (mode(cfg) === 'yggdrasil') {
    emit(
      { node, boundary, dependsOn, written: false },
      flags,
      () => `Yggdrasil mode — this does not write a node. Create `
        + `.yggdrasil/model/${node}/yg-node.yaml (mapping: ${boundary.join(', ')}) and add it to `
        + `yg-architecture.yaml; both need the user's explicit confirmation.`,
    );
    return;
  }

  if (nodeExists(root, cfg, node)) fail(`node already exists: ${node}`);
  writeJSON(manualNodeJsonPath(root, cfg, node), { id: node, boundary, dependsOn, verifiedAt: null });
  const charter = renderTemplate('node-charter', {
    node, owner: '(unassigned)', class: '(unassigned)', lease: '(unassigned)',
  });
  writeText(nodeCharterPath(root, cfg, node), charter);
  writeText(nodeContractsPath(root, cfg, node), renderContractsTable(node, loadGraph(horde).contracts));
  writeText(join(manualNodeDir(root, cfg, node), 'log.md'), `# Log · ${node}\n\n`);
  emit({ node, boundary, dependsOn }, flags, () => `node created: ${node}`);
}

// boundary set|add <node> --boundary <glob>… — the one place a manual-mode node's boundary
// changes after `new`, so a move doesn't need going through node.json by hand. "set" replaces
// the list; "add" extends it, de-duplicated.
function cmdBoundary(horde, root, cfg, sub, positional, flags) {
  const node = positional[0];
  if (!node) fail(`boundary ${sub} requires <node>`);
  if (!flags.boundary) fail(`boundary ${sub} requires --boundary <glob>[,glob…]`);
  const globs = parseBoundaryList(flags.boundary);

  if (mode(cfg) === 'yggdrasil') {
    emit(
      { node, boundary: globs, written: false },
      flags,
      () => `Yggdrasil mode — this does not write a node. ${sub === 'set' ? 'Replace' : 'Extend'} the `
        + `mapping: list in .yggdrasil/model/${node}/yg-node.yaml with: ${globs.join(', ')}; `
        + `needs the user's explicit confirmation.`,
    );
    return;
  }

  if (!nodeExists(root, cfg, node)) fail(`no such node: ${node}`);
  const n = readManualNode(root, cfg, node);
  const before = Array.isArray(n.boundary) ? n.boundary : [];
  n.boundary = sub === 'set' ? globs : [...new Set([...before, ...globs])];
  writeJSON(manualNodeJsonPath(root, cfg, node), n);
  appendText(
    join(manualNodeDir(root, cfg, node), 'log.md'),
    `## [${nowIso()}]\nboundary ${sub === 'set' ? 'set to' : 'extended with'}: ${globs.join(', ')}\n\n`,
  );
  emit({ node, boundary: n.boundary }, flags, () => `boundary ${sub}: ${node} -> ${n.boundary.join(', ')}`);
}

function cmdApply(horde, root, cfg, positional, flags) {
  const id = positional[0];
  if (!id) fail('apply requires <proposal-id>');
  const graph = loadGraph(horde);
  const p = graph.proposals.find((x) => x.id === id);
  if (!p) fail(`no such proposal: ${id}`);
  if (p.status !== 'approved') fail(`proposal ${id} is not approved (status: ${p.status})`);
  if (p.appliedAt) fail(`proposal ${id} was already applied`);

  if (mode(cfg) === 'yggdrasil') {
    p.appliedAt = nowIso();
    saveGraph(horde, graph);
    const step = p.kind === 'move-boundary' && p.node && p.boundary
      ? `set ${p.node}'s mapping: to ${p.boundary.join(', ')} in .yggdrasil/model/${p.node}/yg-node.yaml`
      : `edit .yggdrasil/model/**/yg-node.yaml (and yg-architecture.yaml for a new/renamed/moved node)`;
    emit(
      { id, kind: p.kind, applied: true },
      flags,
      () => `proposal ${id} closed — file it into Yggdrasil yourself: ${step}; needs the user's explicit confirmation.`,
    );
    return;
  }

  // A move-boundary proposal carries the target node and the globs it's moving to (required at
  // propose time), so apply can actually rewrite the boundary — not just mark the proposal done
  // and leave the architect to redo by hand what the proposal already specified.
  if (p.kind === 'move-boundary' && p.node && p.boundary) {
    if (!nodeExists(root, cfg, p.node)) fail(`no such node: ${p.node}`);
    const n = readManualNode(root, cfg, p.node);
    n.boundary = p.boundary;
    writeJSON(manualNodeJsonPath(root, cfg, p.node), n);
    appendText(
      join(manualNodeDir(root, cfg, p.node), 'log.md'),
      `## [${nowIso()}]\nboundary moved (proposal ${id}): ${p.boundary.join(', ')}\n\n`,
    );
    p.appliedAt = nowIso();
    saveGraph(horde, graph);
    emit(
      {
        id, kind: p.kind, applied: true, node: p.node, boundary: p.boundary,
      },
      flags,
      () => `proposal ${id} applied — ${p.node}'s boundary set to: ${p.boundary.join(', ')}`,
    );
    return;
  }

  p.appliedAt = nowIso();
  saveGraph(horde, graph);
  const followUp = p.kind === 'new-node'
    ? `run \`node.mjs new <node> --boundary …\` to create the node's files`
    : `edit the node's files directly (\`node.mjs charter edit\`, or \`new\` again is not needed) to realize "${p.text}"`;
  emit({ id, kind: p.kind, applied: true }, flags, () => `proposal ${id} applied (bookkeeping) — ${followUp}`);
}

// ---- main ---------------------------------------------------------------------

function main() {
  const { positional: allPositional, flags } = parseArgs(process.argv.slice(2), { flags: ['run', 'pending', 'open'] });
  const [cmd, ...rest] = allPositional;

  if (flags.help) { console.log(USAGE); process.exit(0); }
  if (!cmd) fail('missing command (see --help)');

  const horde = resolveHorde(flags);
  const root = repoRoot();
  const cfg = readConfig() || {};

  if (cmd === 'bind') return cmdBind(root, cfg, flags);
  if (cmd === 'map') return cmdMap(horde, root, cfg, flags);
  if (cmd === 'show') return cmdShow(horde, root, cfg, rest, flags);
  if (cmd === 'charter') {
    if (rest[0] !== 'edit') fail('charter requires "edit"');
    return cmdCharterEdit(horde, root, cfg, rest.slice(1), flags);
  }
  if (cmd === 'log') return cmdLog(horde, root, cfg, rest, flags);
  if (cmd === 'stamp') return cmdStamp(horde, root, cfg, rest, flags);
  if (cmd === 'contract') {
    const [sub, ...subRest] = rest;
    if (sub === 'propose') return cmdContractPropose(horde, root, cfg, subRest, flags);
    if (sub === 'approve') return cmdContractRule(horde, root, cfg, subRest, flags, 'approved');
    if (sub === 'veto') return cmdContractRule(horde, root, cfg, subRest, flags, 'vetoed');
    fail('contract requires "propose", "approve" or "veto"');
  }
  if (cmd === 'contracts') return cmdContracts(horde, rest, flags);
  if (cmd === 'propose') return cmdPropose(horde, rest, flags);
  if (cmd === 'proposals') return cmdProposals(horde, flags);
  if (cmd === 'approve') return cmdProposalRule(horde, rest, flags, 'approved');
  if (cmd === 'veto') return cmdProposalRule(horde, rest, flags, 'vetoed');
  if (cmd === 'new') return cmdNew(horde, root, cfg, rest, flags);
  if (cmd === 'boundary') {
    const [sub, ...subRest] = rest;
    if (sub === 'set' || sub === 'add') return cmdBoundary(horde, root, cfg, sub, subRest, flags);
    fail('boundary requires "set" or "add"');
  }
  if (cmd === 'apply') return cmdApply(horde, root, cfg, rest, flags);
  fail(`unknown command: ${cmd} (see --help)`);
}

if (isMain(import.meta.url)) main();
